# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  关于我: /about

# SubNav
subnav:
  github: "https://github.com/jp1017"
  weibo: "http://weibo.com/1321395433/profile?topnav=1&wvr=6"
  mail: "jp19891017@gmail.com"
  rss: "/atom.xml"
  #zhihu: "#"
  jianshu: "http://www.jianshu.com/users/8cb49b5ad78b/latest_articles"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: "http://7xlah4.com1.z0.glb.clouddn.com/favicon.png"

#你的头像url
avatar: "http://7xlah4.com1.z0.glb.clouddn.com/ferrari.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  奥巴马的博客: http://localhost:4000/
  卡卡的美丽传说: http://localhost:4000/
  本泽马的博客: http://localhost:4000/
  吉格斯的博客: http://localhost:4000/
  习大大大不同: http://localhost:4000/
  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…